<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="DESKTOP-P57AQ83" name="Package1.SampleDemo" tests="11" failures="1" timestamp="2021-06-23T21:52:06 IST" time="0.039" errors="0">
  <testcase name="method5" time="0.004" classname="Package1.SampleDemo"/>
  <system-out>
    <![CDATA[shahu]]>
  </system-out>
  <testcase name="method5" time="0.003" classname="Package1.SampleDemo"/>
  <system-out>
    <![CDATA[shahu]]>
  </system-out>
  <testcase name="method5" time="0.002" classname="Package1.SampleDemo"/>
  <system-out>
    <![CDATA[shahu]]>
  </system-out>
  <testcase name="method5" time="0.002" classname="Package1.SampleDemo"/>
  <system-out>
    <![CDATA[shahu]]>
  </system-out>
  <testcase name="method5" time="0.012" classname="Package1.SampleDemo"/>
  <system-out>
    <![CDATA[shahu]]>
  </system-out>
  <testcase name="method2" time="0.002" classname="Package1.SampleDemo"/>
  <system-out/>
  <testcase name="method3" time="0.007" classname="Package1.SampleDemo"/>
  <system-out/>
  <testcase name="method4" time="0.003" classname="Package1.SampleDemo"/>
  <system-out/>
  <testcase name="method1" time="0.004" classname="Package1.SampleDemo">
    <failure type="java.lang.AssertionError" message="expected [13] but found [12]">
      <![CDATA[java.lang.AssertionError: expected [13] but found [12]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at Package1.SampleDemo.method1(SampleDemo.java:16)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- method1 -->
  <system-out>
    <![CDATA[vivek zambre
Ritesh]]>
  </system-out>
  <testcase name="method6" classname="Package1.SampleDemo">
    <skipped/>
  </testcase> <!-- method6 -->
  <system-out/>
  <testcase name="method7" classname="Package1.SampleDemo">
    <skipped/>
  </testcase> <!-- method7 -->
  <system-out/>
</testsuite> <!-- Package1.SampleDemo -->
