<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-P57AQ83" ignored="0" name="Failed" tests="4" failures="1" timestamp="2021-06-27T14:17:13 IST" time="0.092" errors="0">
  <testcase name="Test1" time="0.012" classname="Annotations.Annotation3"/>
  <testcase name="Test2" time="0.003" classname="Annotations.Annotation3"/>
  <testcase name="Test3" time="0.003" classname="Annotations.Annotation3"/>
  <testcase name="Test4" time="0.007" classname="Annotations.Annotation3">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at Annotations.Annotation3.Test4(Annotation3.java:34)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Test4 -->
</testsuite> <!-- Failed -->
