<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-P57AQ83" ignored="3" name="Default test(failed)(failed)(failed)" tests="1" failures="1" timestamp="2021-06-27T14:12:18 IST" time="0.068" errors="0">
  <testcase name="Test4" time="0.016" classname="Annotations.Annotation3">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at Annotations.Annotation3.Test4(Annotation3.java:34)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Test4 -->
  <testcase name="Test1" time="0.0" classname="Annotations.Annotation3">
    <ignored/>
  </testcase> <!-- Test1 -->
  <testcase name="Test3" time="0.0" classname="Annotations.Annotation3">
    <ignored/>
  </testcase> <!-- Test3 -->
  <testcase name="Test2" time="0.0" classname="Annotations.Annotation3">
    <ignored/>
  </testcase> <!-- Test2 -->
</testsuite> <!-- Default test(failed)(failed)(failed) -->
